[package]
name = "rust_async_practice"
version = "0.1.0"
authors = ["Wonchul Lee <wonchul.dev@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
futures = "0.3.4"
async-std = "1.5.0"
